package com.hamid.usermanagement.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * User
 *
 * =========================================================
 * WHY THIS CLASS IS REQUIRED
 * =========================================================
 *
 * This class represents the USER table in the database.
 *
 * In JPA:
 * --------
 * - An Entity = a database table
 * - Each object of this class = one row in the table
 *
 * This entity is used by:
 * ----------------------
 * - Repository layer (for DB operations)
 * - Service layer (business logic)
 *
 * IMPORTANT:
 * ----------
 * Entity should NOT be used directly in API requests or responses.
 * DTOs are used instead to protect database structure.
 */
@Data                   // Generates getters, setters, equals, hashCode, toString
@Entity                 // Marks this class as a JPA entity (DB table)
@Table(name = "users")  // Maps this entity to "users" table
@AllArgsConstructor     // Constructor with all fields
@NoArgsConstructor      // Required by JPA for entity creation
public class User {

    /**
     * Primary key of the users table.
     *
     * @Id -> Marks this field as primary key
     * @GeneratedValue -> Value is auto-generated by database
     * IDENTITY strategy lets database handle auto-increment
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * User's full name.
     *
     * Stored as a column in users table.
     * No explicit annotation means default column settings.
     */
    private String name;

    /**
     * User's email address.
     *
     * @Column(unique = true)
     * ---------------------
     * - Ensures email is unique in database
     * - Prevents duplicate user accounts
     *
     * @Column(nullable = false)
     * -------------------------
     * - Email must always have a value
     * - Database will reject null emails
     *
     * Email is used as login identifier.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Encrypted password.
     *
     * IMPORTANT:
     * ----------
     * - This is NOT plain text password
     * - Value stored here is BCrypt hash
     *
     * Example:
     * --------
     * $2a$10$XyZabc...
     */
    private String password;

    /**
     * User role.
     *
     * Example values:
     * ---------------
     * - USER
     * - ADMIN
     *
     * Used for authorization (role-based access control).
     */
    private String role;
}
